### PR TITLE
Created a txt file with my name - Lorenzo

### PR DESCRIPTION
**Pull request by loredt90**

### CODE REVIEW

**Review by linda035 — APPROVED** [review]
Great job :)

**Comment by loredt90** [comment]
Thank you for your approval, Linda! =)

**Review by pgangarella — APPROVED** [review]
go on

**Review by demetrio-marra — APPROVED** [review]

**Review by TeobaldoIlGiovane — APPROVED** [review]

**Review by BladeBaT — APPROVED** [review]
seems all ok, APPROVED!

**Pull request merged**
